### ISSUE TITLE
On Ubuntu 16.04,  Qsim test fails with a segfault   

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#106]
This is with gcc-5.3.1.  
(was originally in issue #95, which is now closed.)

Trace back from qsim segmentation fault:
 RUN SST 
 [ubuntu1604B:110576] **\* Process received signal ***
 [ubuntu1604B:110576] Signal: Segmentation fault (11)
 [ubuntu1604B:110576] Signal code: Address not mapped (1)
 [ubuntu1604B:110576] Failing at address: 0x74
 [ubuntu1604B:110576] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10cd0) [0x7f8dbe77fcd0]
 [ubuntu1604B:110576] [ 1] /tmp/qsim_bDfBDR(run+0x15) [0x7f8cb13c69a5]
 [ubuntu1604B:110576] [ 2] BASE/local/packages/Qsim/lib/libqsim.so(Qsim::OSDomain::run(unsigned short, unsigned int)+0x170) [0x7f8db33e5be0]
 [ubuntu1604B:110576] [ 3] BASE/local/packages/Qsim/lib/libqsim.so(Qsim::load_file(Qsim::OSDomain&, char const)+0x24f) [0x7f8db33eb3bf]
 [ubuntu1604B:110576] [ 4] BASE/local/lib/sst/libqsimComponent.so(SST::QsimComponent::qsimComponent::init(unsigned int)+0x76) [0x7f8db5877796]
 [ubuntu1604B:110576] [ 5] BASE/local/bin/sst(SST::Simulation::initialize()+0x91) [0x6b7151]
 [ubuntu1604B:110576] [ 6] BASE/local/bin/sst() [0x5d7260]
 [ubuntu1604B:110576] [ 7] BASE/local/bin/sst(main+0x1ef8) [0x5c9a58]
 [ubuntu1604B:110576] [ 8] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8dbca78a00]
 [ubuntu1604B:110576] [ 9] BASE/local/bin/sst(_start+0x29) [0x5d6069]
 [ubuntu1604B:110576] *\* End of error message ***

BASE/devel/trunk/test/testSuites/testSuite_qsimComponent.sh: line 64: 110576 Segmentation fault (core dumped) ( ${sut} -n 1 ${sutArgs} > ${outFile} )

**Comment by allevin** [comment]
QSim is now in the archive.  This issue is closed.
