### ISSUE TITLE
Is it possible to use merlin only?

### ISSUE THREAD

**Issue by Xiaoyang-Lu** [sstsimulator/sst-elements#1077]
My rough plan is to simulate a system as below: Each machine has locally attached memory, with a part assigned to a pool of cluster memory. Machines are connected by a commodity network. So I want to know how to simulate the network traffic (congestion) between the different nodes, I know Merlin may has simple traffic generation models (I don't know the simple traffic generation model is enough or not)? Or just using Merlin to bridge nodes simply is enough? I cannot find any example or documents about that, so could you give me any suggestion or give a specific example about that? 
![image](https://user-images.githubusercontent.com/21236923/42170768-1b11fb06-7ddd-11e8-9b1b-fe0f87203b6b.png)
Thanks.

**Comment by nmhamster** [comment]
What topology would you like to connect the memories and processors with?

**Comment by Xiaoyang-Lu** [comment]
@nmhamster I use star topology now.

**Comment by nmhamster** [comment]
You should be able to configure a Merlin Torus topology with a single router and `N` ports that mean everything can get routed directly.

**Comment by Xiaoyang-Lu** [comment]
@nmhamster Yes. I used a single router and configured the simplest star topology, connected the nodes to this router directly.

**Comment by allevin** [comment]
No further response from author, closing this issue.
