### ISSUE TITLE
Help needed for simulating HMC system

### ISSUE THREAD

**Issue by saurabhgangurde** [sstsimulator/sst-elements#1096]
I want to simulate system which can offload instructions to HMC . Any suggestions how can I start? Which simulator should I use for core (Ariel or Macsim or other)? How to use that simulator with VaultSimC?
Thanks

**Comment by hughes-c** [comment]
@saurabhgangurde, it depends on what you want to do. You can look in sst-elements/src/sst/elements/VaultSimC/tests for some examples on how to connect VaultSim components.

**Comment by nmhamster** [comment]
@saurabhgangurde - did this help fix the question you asked? I'll close this issue and you can re-open if you wanted additional help.
