### ISSUE TITLE
Trac: #242 Need WIKI component documentation for Merlin

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#11]
Provide the whatwhy summary, followed by the how, sample input deck andor anything else you think will illuminate the function of the component. First, check out the one line summary at https:sst-simulator.orgwikiDeveloperComponentSummaryInfo and then click on the component link to access the documentation page for that component.

**Comment by hughes-c** [comment]
https://sst-simulator.org/sst-docs/docs/elements/merlin/intro
