### ISSUE TITLE
sst link latency between the componets

### ISSUE THREAD

**Issue by tks2004** [sstsimulator/sst-elements#1140]
How do I choose the sst link latency in seconds between the components. For example, the link between core and the L1 cache and L1 to L2.

**Comment by hughes-c** [comment]
@tks2004 You set the latency when you create the link and setup the connection.
l1_l2_link.connect( (l1cache, "low_network_0", "50ps"), (l2cache, "high_network_0", "50ps") )

**Comment by tks2004** [comment]
Is 50ps applicable to all the links for the components. core ->L1 -> L2 -> L3 ->memory controller

Is 50ps based on any formula or is it the default value to be considered for SST 8.0

**Comment by hughes-c** [comment]
50ps is a sane value if you have a simple bus. However, more complicated on-chip networks can have higher latencies, it depends on what you're trying to model.

The link latency can affect simulation time.

**Comment by tks2004** [comment]
L3 is a shared, Do you suggest to use NoC using Merlin router or can I link the l2 of each core to L3 through a bus?

**Comment by hughes-c** [comment]
@tks2004 It really depends on what you are trying to model. Older microarchitectures, such as Nehalem, were organized around a bus such as the image below:

![nehalem-microarchitecture-11-638](https://user-images.githubusercontent.com/25310538/46886070-0350d980-ce17-11e8-9254-316344cd2abf.jpg)

Modern microarchitectures are organized using a ring or a mesh, such as the Skylake microarchitecture below:

![image](https://user-images.githubusercontent.com/25310538/46886146-398e5900-ce17-11e8-93d6-79619f1a2828.png)

We provide several example system models with SST. For Ariel, we have a bus example in runstream.py and rings in ariel_ivb.py and ariel_snb.py. We also have a mesh model in the kingsley folder, noc_mesh_32_test.py. If you describe what you are trying to model, we may be able to provide more help.

**Comment by tks2004** [comment]
Iam trying to model AMD EPYC a zeppelin die that has infinity fabric used for the data transmission for the linked components 
https://en.wikichip.org/wiki/File:amd_zeppelin_basic_block_4-dies.svg

![image](https://user-images.githubusercontent.com/19617108/46906749-549bbe80-cf26-11e8-89be-a47071128a99.png)

**Comment by tks2004** [comment]
I have simulated a model using prospero  cpu for 8 cores with local L1 and L2 cache. L3 is shared and DRAMSim2. Had created a binary traces (8 trace files) using PIN for a OpenMP based application. When I simulate, the simulated time is same for 1 core and for 8 cores (Simulation is complete, simulated time: 75.7914 ms), Is this expected?

**Comment by tks2004** [comment]
Yes Cycles with ops issued and Cycles with no ops issued are different.
- Completed at:                          75791448 ns
- Cycles with ops issued:                4070276 cycles
--
- Completed at:                          75791448 ns
- Cycles with ops issued:                4152742 cycles
--
- Completed at:                          75791448 ns
- Cycles with ops issued:                37286388 cycles
--
- Completed at:                          75791448 ns
- Cycles with ops issued:                3147133 cycles

**Comment by nmhamster** [comment]
@hughes-c - did we get this bug cleared up?

**Comment by allevin** [comment]
No further response from author, closing this issue.
