### ISSUE TITLE
Element name in miranda starts with uppercase M

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-elements#116]
In miranda's ElementLibraryInfo structure (miranda.cc), the name of the element is "Miranda".  However, the compiled library is called libmiranda.so.  Note that libmiranda.so is all lowercase.

SST Workbench uses this name in the ElementLibraryInfo to build the python file and set the sst.Component(...)

The constructed python becomes `sst.Component("Miranda.BaseCPU.8", "Miranda.BaseCPU")`  Which when run, will give an error that libMiranda.so cannot be found.

To resolve the issue, the ElementLibraryInfo should have the element name changed from Miranda to miranda.

**Comment by nmhamster** [comment]
Fix merged in PR #124
