### ISSUE TITLE
Trac: #248 Need WIKI component documentation for VaultSim

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#12]
Provide the whatwhy summary, followed by the how, sample input deck andor anything else you think will illuminate the function of the component. First, check out the short summary at https:sst-simulator.orgwikiDeveloperComponentSummaryInfo and then click on the component link to access the documentation page for that component.

**Comment by allevin** [comment]
Limited Documentation exists, closing this issue.
