### ISSUE TITLE
Scheduler Component does not work with multi-thread for n>1

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#122]
Because the scheduler,  "is not thread safe".    The actually problem may be zero latency links.

**Comment by nmhamster** [comment]
John - can you describe what's not thread safe in the DetailedNetwork? Is this something we can (easily) fix?

**Comment by jpvandy** [comment]
It was possible to allow the Detailed Network test to use multithread only on the ember part of the test, which is where most of the compute time is used and not use multiple threads on the scheduler part of the test.

This is currently regarded as an acceptable state of the Scheduler for Release 6.0.

I am not closing this issue at this time, because there is an SST restriction here that needs to be appropriately documented (somewhere).

**Comment by nmhamster** [comment]
Moved to SST v7.0.0 because this will not be completed by release time. Requires more in-depth code changes.
