### ISSUE TITLE
Missing return warnings for GCC for switch statements 

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-elements#1255]
Several switch statements do not provide a trailing return or default case statement, leading GCC to spew complaints about missing return statements in memOp.h, nicEvents.h, and shmemapi.h

**Comment by hughes-c** [comment]
@jjwilke Should this go into 9.1?

**Comment by jwilso** [comment]
@jjwilke @hughes-c Was this ever addressed? I will leave it open if so.

**Comment by hughes-c** [comment]
@jwilso Not that I'm aware of.

**Comment by nmhamster** [comment]
@allevin / @jjwilke - do we have a list of these we can knock out for the release?

**Comment by allevin** [comment]
@jjwilke do you know what version of the gcc compiler was throwing the complaints?   
I will try to do a warnings scrub next week.

**Comment by allevin** [comment]
@jjwilke @nmhamster I cannot reproduce these build warnings.  I tried GCC 4.8 and GCC 6.1... The issue was submitted in 2019, and may have been cleaned up since.  I recommend closing.
