### ISSUE TITLE
McOpteron test2 current fails on Linux as well as MacOS

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#129]
Test had not been run in a very long time.  The Suppression of the test on MacOS (Issue #76)  inadvertently omit testing on Linux also.

Test will be explicitly omited on all platforms

**Comment by nmhamster** [comment]
@jpvandy can you please post the error output you are seeing here so we can view it? Thank you!

**Comment by jpvandy** [comment]
This file was created from a current sandbox.   It is very similar (or identical) with a Jenkins failure on February 21st before we stopped running the test.

[mcO-test2-current-output.txt](https://github.com/sstsimulator/sst-elements/files/205019/mcO-test2-current-output.txt)

**Comment by nmhamster** [comment]
Moved to attic, shelving until fixed in the future.
