### ISSUE TITLE
Miranda and Ariel Examples for Sandy Bridge, Ivy Bridge and KNC are Not in Distribution

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#135]
Need to provide example Python files for our SNB, IVB and KNC models.

**Comment by jpvandy** [comment]
The example inputs for Ariel are there.  There simply buried more deeply in  

 elements/ariel/frontend/simple/examples/stream/

**Comment by jwilso** [comment]
Arun: Should make these easier to find, and add KNC.

**Comment by nmhamster** [comment]
Decision made to post these to the website *after* the SST v6.0 release has been posted and then to work on including them in future releases. Changed to SST v6.1.0.

**Comment by nmhamster** [comment]
These will be posted in an online repository of models to be added during SST v7.0, not being done for SST v6.0/v6.1.

**Comment by hughes-c** [comment]
@nmhamster Ivy Bridge and Sandy Bridge models are in the ariel test folder and have been there since https://github.com/sstsimulator/sst-elements/commit/87130be2c4bd6e3ae5120cf9d847912f7c39a07f. We have a KNL model that we can add.

**Comment by allevin** [comment]
@gvoskuilen  to take care of this.

**Comment by hughes-c** [comment]
Closing this. Will update with more modern processor models.
