### ISSUE TITLE
SST McNiagara Model Needs to be Removed from Devel Branch

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#137]
Confirmed with Jeanine that we are going to remove SST McNiagara but need to ensure that this works correctly with any changes to SQE repo.

@jpvandy @allevin - we need to work out what process has to take place for this work successfully with the auto-tester.

**Comment by nmhamster** [comment]
Removed.

**Comment by allevin** [comment]
The McNiagara element has been copied over to the sst-elements-archive repository
