### ISSUE TITLE
Remove metis/remove scheduler

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-elements#1447]
We have discussed removing scheduler. Scheduler is also the only place where `metis.h` is included.  We could also remove the dependence on metis.

**Comment by allevin** [comment]
Scheduler is currently marked as depricated, and will be removed in SST-11

**Comment by nmhamster** [comment]
@jjwilke / @allevin - we may use Metis in the core for partitioning, somewhere I have a version of the code for that (agree - we probably want to remove from Elements though).

**Comment by gvoskuilen** [comment]
Removed
