### ISSUE TITLE
The simpleComponent test is not deterministic for multhread n>1

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#148]
The output appears to depend on a shared counter and the simple result of n=1 may vary when n>1.
According the c++ code, there are supposed to be 9 lines of "Simple Component Finished", (plus two other lines.)  For n>1 the number of lines has been observed to be from 9 to 12.

**Comment by afrodri** [comment]
Output changed to simply print "Component Finished", without the shared counter.
