### ISSUE TITLE
scatter not working for any other root except 0

### ISSUE THREAD

**Issue by khodarkhashi** [sstsimulator/sst-elements#1485]
I am trying to use enQ_scatter for my simulation along a custom communicator. But it gets into segfault. When I use GroupWorld and 0 as root it works fine. My guess is scatter only works for GroupWorld and root as 0. Since using a custom communicator does not ensure the root as 0 , that results into a segfault.

**Comment by jjwilke** [comment]
Can you post a minimal reproducer code and Python file?

Custom communicators are probably more heavily tested in SST/macro skeletons - so there are other options to get you started if we can't get this working.

**Comment by nmhamster** [comment]
@mjleven - this sounds like a FireFly bug?

**Comment by nmhamster** [comment]
Please see PR: #1511 - thank you to Mike Levenhagen for working through this issue.

**Comment by nmhamster** [comment]
Issued closed with #1511
