### ISSUE TITLE
Trac: #282 Tests/Verify the LLSC feature from MemHierarchy

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#15]
Once the LLSC feature has been put in place, this locking mechamism needs to be tested on the current sweeps (w and wo directory) 

Tests outputs should match the reference files even when this feature is activated.

**Comment by allevin** [comment]
This need some research, into how LLSC is implemented and how to knowingly interact with it. No existing test were identified as failing for its lack before it was add June 18th The added code appears to have introduced no new failures.

**Comment by allevin** [comment]
Documentation exists, closing issue.

**Comment by gvoskuilen** [comment]
This has been resolved; the LL/SC instructions are tested.
