### ISSUE TITLE
SST Patterns should be moved to the Elements Attic

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#152]
Move Patterns into the legacy elements attic. No longer supported as of SST v6.0.0.

**Comment by nmhamster** [comment]
This issue is going to hold up the external-elements work because there is an m4 macro in patterns for detecting where MPI is enabled by SST. I need to make sure we get this out ASAP.

**Comment by allevin** [comment]
Pull Request 156 corrects the issue.
