### ISSUE TITLE
Trac: #297 MemHierarchy support for FLUSH cpu instruction

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#16]
MH should support flushing. This functionality is required by some OSesCPUs 

An L1 should look at all its cache lines and writeback any valid ones. Potential issues: 

A) The cache line is in transient state. Cache should probably wait for response before writing back 
B) Cache should temporarily disable other incoming requests (prefetcher, cpu) while flushing 
C) Assert that no cache lines have a LOCK bit 
D) How many writebacks to send per cycle Gotta be careful not for overflowdeadlock situations

**Comment by allevin** [comment]
Moved to SST v6.0 but discussion underway for how to implement. Possibly need for non-volatile flushing and SST checkpointing studies.

**Comment by nmhamster** [comment]
Initial support now included in MemHierarchy for SST v7.0 release.
