### ISSUE TITLE
SST-elements: prefetch latency is not recorded (bug)

### ISSUE THREAD

**Issue by daecheolyou** [sstsimulator/sst-elements#1667]
In SST elements, the coherenceController records prefetch latency with recordPrefetchLatency(). However, this doesn't work since there is no startTimes_ map entries for prefetch requests. Unlike  handleEvent() in cacheController, which calls recordIncomingRequest() for an incoming request, handlePrefetchEvent() does not call recordIncomingRequest(), and thus corresponding latency is not collected.
I think the handlePrefetchEvent() should also call recordIncomingRequest() for correct stat gathering.

**Comment by gvoskuilen** [comment]
@daecheolyou Thank you for submitting this, I will take a look and fix.
