### ISSUE TITLE
Elements that need python to enable shared libraries should check for that at configure time. 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-elements#1678]
1 - Detailed description of problem or enhancement

Making elements and I get the following error
```
libpython3.9.a(import.o): relocation R_X86_64_32S against symbol `PyDict_Type' can not be used when making a shared object; recompile with -fPIC
```

2 - Describe how to reproduce

I didn't try in depth to figure out how to make this work, but I believe all you need is a python that was not built with `--enable-shared` and then use that python with core. 

I believe this could be detected sooner than the elements linking step. Which is why I made this issue.

**Comment by hughes-c** [comment]
@feldergast do we care about this?

**Comment by feldergast** [comment]
We haven't seen any issues with this.
