### ISSUE TITLE
c_AddressHasher.hpp missing include 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-elements#1712]
New Issue for sst-elements
--------------------------

1 - CramSim.cpp fails to build due to undefined uint type
```
 error: 'uint' was not declared in this scope; did you mean 'int'?
            void parsePattern(std::string *x_inStr, std::pair<std::string, uint> *x_outPair);
  ```

3 - alpine linux docker image

The header `sys/types.h` is available but not included.  This was fixed by just including that header.

**Comment by calewis** [comment]
Although `uint` isn't considered portable and should really be changed to unsigned int. Or the typedef should be provided by the library itself.

**Comment by calewis** [comment]
c_TxnGen.cpp has the same issue

**Comment by calewis** [comment]
As does GNA.h

**Comment by calewis** [comment]
ariel_shmem.h is missing sys/time.h

**Comment by hughes-c** [comment]
I remember fixing some of those CramSim types a year or so ago but I guess I never pushed them.
