### ISSUE TITLE
Segmentation Fault when running Opal example Test

### ISSUE THREAD

**Issue by tchandrahas** [sstsimulator/sst-elements#1733]
Hello all,
I am new to SST and I am trying to setup system simulations with Opal. However, I am encountering segmentation fault when running the example test of Opal. 
Interestingly, the segmentation fault is occurring on the Ariel CPU. After some debugging I found out that line `tunnel->writeMessage(0,ac)` of `Fini` function in `src/sst/elements/ariel/frontend/pip3/fesimple.cc` responsible for this fault.

To reproduce this error. navigate to the folder `src/sst/elements/Opal/tests` and run `sst --output-directory=opal_test_outputs/ basic_1node_1smp.py --verbose`

I am using pin tool version 3.18. gcc version 11.2.0.

**Comment by nhatdangncsu** [comment]
Hi, I am having a similar problem too. I want to ask how you resolve this issue.
