### ISSUE TITLE
Qsim and MacSim disabled to build sst with the new serialization

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#174]
Qsim and MacSim have not been converted to compile with the new serialization.

**Comment by jpvandy** [comment]
Qsim has been adapted to current repo and has been restored to the nightly.    It runs on Linux.  It is slower on multiple cores or multiple ranks, the the runs finish and thee test still passes.

**Comment by jwilso** [comment]
Arun: Qsim appears to be updated, but not MacSim.

**Comment by nmhamster** [comment]
MacSim will not be supported for v6.1 series as it will now become an external element.
