### ISSUE TITLE
Vanadis faults when running HPCG

### ISSUE THREAD

**Issue by mjleven** [sstsimulator/sst-elements#1749]
New Issue for sst-elements
--------------------------

1 - Detailed description of problem or enhancement
When running HPCG on Vanadis it faults at address 0x511218 which is in funciont alloc_slot in libc.

2 - Describe how to reproduce
Compile HPCG using the Make.Linux_Serial make file as the base Makefile. 

Make these changes:

[mjleven@sst-devel-new setup] (master)*$ diff Make.musl Make.Linux_Serial 
120c120
< CXX          = mipsel-linux-musl-g++ 
---
> CXX          = /usr/bin/g++
123c123
< LINKER       = $(CXX) -static
---
> LINKER       = $(CXX)
[mjleven@sst-devel-new setup] (master)*$ 

Use the vanadis/tests/basic_vanadis.py as the SST run script.

3 - What Operating system(s) and versions 

Run on sst-devel-new

4 - What version of external libraries (Boost, MPI)

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by hughes-c** [comment]
This was fixed by a series of PRs.
