### ISSUE TITLE
Vanadis does not properly format StandardMem Request for an open system call

### ISSUE THREAD

**Issue by mjleven** [sstsimulator/sst-elements#1815]
When running IMB PingPong compiled with MUSL C Vanadis OS creates a StandardMem Request that spans a cache line.

[node-os]: Call from core: 0, thr: 0 -> calling handler...
[node-os-core-     0]: -> call is open()
[node-os-core-     0]: [syscall-open] -> call is open( 0x4378c8, 532608 )
[node-os-core-     0]: sending request: ID: 62352, Type: Read, Flags: [] PhysAddr: 0x4378c8, VirtAddr: 0x0, Size: 8, InstPtr: 0x0, ThreadID: 0
[node-os]: redirecting to core 0...
[node-os-core-     0]: recv memory event (ID: 62352, Type: ReadResp, Flags: [] PhysAddr: 0x4378c8, VirtAddr: 0x0, Size: 8, InstPtr: 0x0, ThreadID: 0, Payload: 0x2f6574632f6c6f63)
[os-func-handler]: [syscall-open] request processing...
[node-os-core-     0]: sending request: ID: 62356, Type: Read, Flags: [] PhysAddr: 0x4378d0, VirtAddr: 0x0, Size: 64, InstPtr: 0x0, ThreadID: 0
FATAL: Error: In memHierarchy Interface (node0.cpu0.os:mem_interface), Request cannot span multiple cache lines! Line mask = 0xffffffffffffffc0. Event is: <65030,0> GetS Src: node0.cpu0.os:mem_interface Dst: node0.cpu0.node_os.l1dcache Rq: node0.cpu0.os:mem_interface Flags: [] Addr: 0x4378c0/0x4378d0 (G) Data: F VA: 0x0 IP: 0x0 Size: 64 Prf: F

The bug can be fixed with the following:

[mjleven@sst-devel-new tests] (v_storebuff)*$ git diff ../../vanadis/os/vnodeoshandler.h 
diff --git a/src/sst/elements/vanadis/os/vnodeoshandler.h b/src/sst/elements/vanadis/os/vnodeoshandler.h
index e60bf13..1584f4b 100644
--- a/src/sst/elements/vanadis/os/vnodeoshandler.h
+++ b/src/sst/elements/vanadis/os/vnodeoshandler.h
@@ -290,7 +290,11 @@ public:
                 = new VanadisOpenHandlerState(output->getVerboseLevel(), open_ev->getPathPointer(), open_ev->getFlags(),
                                               open_ev->getMode(), &file_descriptors, handlerSendMemCallback);
 
-            const uint64_t start_read_len = (open_ev->getPathPointer() % 64) == 0 ? 64 : open_ev->getPathPointer() % 64;
+            //const uint64_t start_read_len = (open_ev->getPathPointer() % 64) == 0 ? 64 : open_ev->getPathPointer() % 64;
+
+            const uint64_t start_read_len
+                = (open_ev->getPathPointer() % 64) == 0 ? 64 : 64 - ( open_ev->getPathPointer() & (64-1) );
+
 
             StandardMem::Read* open_start_req
                 = new StandardMem::Read(open_ev->getPathPointer(), start_read_len);
[mjleven@sst-devel-new tests] (v_storebuff)*$

**Comment by nmhamster** [comment]
Fixed in update to Vanadis code in `devel`. Will close.
