### ISSUE TITLE
Component c'tor now needs an argument

### ISSUE THREAD

**Issue by pdbj** [sstsimulator/sst-elements#1847]
The Component c'tor with no argument for id is now deprecated.

Patch [here](https://github.com/pdbj/sst-elements/commit/86f8ba3c3abd280bda717c87f8a9d4f8b27d198c)

**Comment by gvoskuilen** [comment]
@pdbj Can you expand on this issue a bit? There shouldn't be no-argument constructors for components and the default constructor shouldn't be getting created. I'm not sure where you see one invoked? Thanks.

**Comment by pdbj** [comment]
Sorry, I see that these two have been fixed.
