### ISSUE TITLE
sst.sandia.gov subpages point to old unused urls

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-elements#187]
Google searching for various sst tools (for example dumpi) takes the user to subpages of the sst.sandia.gov site.  The top page tells the user to goto sst-simulator.org, but there are direct links on the sidebar and subpages which have obsolete information (see http://sst.sandia.gov/about_core.html).

These pages and website needs to be revamped.

**Comment by jwilso** [comment]
Aaron:  Let @nmhamster make the determination.
