### ISSUE TITLE
MMAP Syscall Implementation in Vanadis

### ISSUE THREAD

**Issue by Connie120** [sstsimulator/sst-elements#1892]
Hello! I'm trying to simulate a very basic program that's compiled with LLVM using Vanadis, and the simulation stops with an error message indicating that the MMAP syscall (code 222) is not implemented yet. I've also taken a look at the code in the current devel branch, and multiple syscalls are prepended with an "assert(0)", so I'm guessing they're still under construction? Is there a version in the repo that's able to simulate the MMAP syscall? Thank you very much!

**Comment by hughes-c** [comment]
Pretty sure this was fixed in 82f09ccacf8a2c1a3ecb6382c1a9d2a75ac2a70d.
