### ISSUE TITLE
Simulating Multi-threaded Program on Vanadis

### ISSUE THREAD

**Issue by Connie120** [sstsimulator/sst-elements#1893]
Hello! I'm trying to add this functionality to run multiple threads in parallel on Vanadis, and given the current situation that Vanadis is not able to simulate pthread programs due to some unimplemented syscalls, I'm thinking loading a single-thread program and expand it into multiple threads to test for now. Any advice on how should I approach this in a better way? Any help would be appreciated, thank you!

**Comment by plafratt** [comment]
Is this resolved? In case it isn't, I thought I should make a note that I was able to successfully use pthread_create(). There is a test in the repository in `vanadis/tests/small/misc/pthread/` that I found helpful.

**Comment by Connie120** [comment]
@plafratt This has been resolved, thanks for mentioning!
