### ISSUE TITLE
Merlin::Bridge undefined symbol (non-lazy binding)

### ISSUE THREAD

**Issue by jpkenny** [sstsimulator/sst-elements#1898]
On systems that are more strict about symbol resolution (namely OS X 12/Monterey), runtime errors like the following occur when loading element libraries:

dlopen(/Users/jpkenny/install/sst-elements-devel/lib/sst-elements-library/libmemHierarchy.so, 0x0009): symbol not found in flat namespace '__ZN3SST6Merlin6BridgeC1EyRNS_6ParamsE'

**Comment by gvoskuilen** [comment]
Fixed
