### ISSUE TITLE
MemHierarchy SDL Generator

### ISSUE THREAD

**Issue by kaustubhcs** [sstsimulator/sst-elements#1912]
All sdl test cases present in memHierarchy (sdl*.py) are tagged with "Automatically generated SST Python input"
But I cannot find the test case generator script in the sst-elements repository for memHierarchy.
I was wondering what scripts/software was used to generate these SDL files?

**Comment by feldergast** [comment]
I think those comments have largely been removed in the latest release of SST.  Those comments come from quite a while ago when we transitioned from XML to python as the input language for SST.  They were generated using an older version of the --output-config option available in the sst executable that writes the internal input graph format (in the case of those test files generated from reading the XML) to a python input file.  There were no external tools used to generate the tests, just a translation from one input format to the another.  If you use the --output-config option in SST, you'll still get a similar comment in the resulting file ("# Automatically generated by SST").
