### ISSUE TITLE
memNIC passes the wrong parameters to linkcontrol

### ISSUE THREAD

**Issue by tomhaber** [sstsimulator/sst-elements#1916]
On lines 
https://github.com/sstsimulator/sst-elements/blob/47f2a11e34c5d45d3c3db7f9ca1f9051dd1c1574/src/sst/elements/memHierarchy/memNIC.cc#L44
and
https://github.com/sstsimulator/sst-elements/blob/47f2a11e34c5d45d3c3db7f9ca1f9051dd1c1574/src/sst/elements/memHierarchy/memNIC.cc#L45

It should be "input_buf_size" and "output_buf_size"

**Comment by jleidel** [comment]
@tomhaber, this has been merged into `devel`.  I would wait until the next merge to `master` before you attempt to utilize the feature.
