### ISSUE TITLE
Using MMIO device with Vanadis

### ISSUE THREAD

**Issue by William-An** [sstsimulator/sst-elements#2034]
Using MMIO device with Vanadis
--------------------------

1 - Detailed description of problem or enhancement

Hi All, I am working on getting the MMIO version balar to work with Vanadis. My previous solution was to add a router between CPU and the L1D cache to allow LD/ST towards MMIO to bypass the cache. This works great before I sync up with the newest devel branch, which introduces TLB to Vanadis.

My question now is can I still add the router between the CPU DTLB and L1D with the current Vanadis core? I did attempt this but failed since the TLB is not using `standardInterface` to connect to the cache. Or does a different solution exist?

2 - Describe how to reproduce

N/A

3 - What Operating system(s) and versions 

Ubuntu 18.04

4 - What version of external libraries (Boost, MPI)

N/A

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

sst-core git commit hash: [0f358dda178f96db3b0da88b2b965492c4be187d](https://github.com/sstsimulator/sst-core/tree/0f358dda178f96db3b0da88b2b965492c4be187d)
sst-elements: https://github.com/William-An/sst-elements/tree/balar-mmio (sync with [5b87363597c6a6f8be23887b64153147a0a765aa](https://github.com/sstsimulator/sst-elements/tree/5b87363597c6a6f8be23887b64153147a0a765aa))

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by hughes-c** [comment]
@William-An are you still hung on this or can it be closed?
