### ISSUE TITLE
DiskSim/SSDSim

### ISSUE THREAD

**Issue by FDZX0118** [sstsimulator/sst-elements#2088]
hello 

I know from section 4.3 of the paper [1] that DiskSim is integrated into the SST, but I can't find where it is and how to configure it.
Can you help me? Please

[1]"The structural simulation toolkit. SIGMETRICS Perform. Eval. Rev. 38, 4 (March 2011), 37–42. https://doi.org/10.1145/1964218.1964225"

**Comment by gvoskuilen** [comment]
At one time DiskSim was integrated with SST, but it is no longer integrated or supported.

**Comment by FDZX0118** [comment]
Thank you very much for your reply. Please tell me where can I find the old version of SST with DiskSim integration? Or can you share it with me? Thanks again!

**Comment by hughes-c** [comment]
@FDZX0118 previous releases of sst are here: https://github.com/sstsimulator/sst-elements/releases or http://sst-simulator.org/SSTPages/SSTBuildAndInstall_older_downloads/ 

I don't see anything in the release notes on ssdsim so I don't know the last version that supported it.
