### ISSUE TITLE
Issues with multi-thread simulation of Ariel, Samba, Opal components 

### ISSUE THREAD

**Issue by tchandrahas** [sstsimulator/sst-elements#2089]
Hello all, 
I am trying to simulate a multi-core processor system that comprises of Ariel, Samba, Opal, memHierarchy, merlin components. My system configuration script runs perfectly when I am using  1 sst simulation thread, with sst.linear partitioner. 

In an attempt to parallelize the simulation, I did the following changes to my system configuration

-  I used `sst.component.setRank(..)` on each of my simulation component to statically assign rank and thread. In my case, I am using single rank, hence I am just changing the thread number across different simulation components.
-  I changed the partitioner to `sst.self` to allow the static partitioning that I made
-  I changed sst simulation command to `mpirun -n 1 sst --num_threads=20 --inter-thread-links=true`. The simulation  isn't working if I remove `inter-thread-links=true` option. 

With these changes, the simulation starts and runs improperly. The events aren't getting to each of the simulation component. But the heartbeat increments and I can see the debug prints that I have kept in one of the custom sst component. The Ariel cores aren't issuing any loads/stores with exception of few initial instructions  on core-0. Not exactly sure on whats causing this behavior. 
In my output file I see bunch  of `*** Event queue empty, exiting simulation... ***` print outputs. This can possibly mean that some simulation components shut down during my simulation. Does this mean that my simulation is not parallelizable? 

Let me know if there is anything that can I do to fix my script to enable parallelization

**Comment by gvoskuilen** [comment]
@tchandrahas I believe this was fixed by changing your python script? Can the issue be closed or are you still encountering issues?
