### ISSUE TITLE
SST-GPGPUSim Integration

### ISSUE THREAD

**Issue by FDZX0118** [sstsimulator/sst-elements#2090]
Hello 

I can't find the configuration file "cuda-test.py" mentioned in Tutorial_03_integration[1], could you share a copy with me, please?

[1]https://github.com/sstsimulator/sst-downloads/releases/download/Documentation/PACT_2019_Tutorial_03_integration.pptx
P14: sst --model-option="-c ariel-gpu-v100.cfg -s abs_kviTA.csv -x ./vectorAdd-163840" cuda-test.py

**Comment by William-An** [comment]
Here is the `cuda-test.py` from a previous commit: https://github.com/sstsimulator/sst-elements/blob/a231e530231322985441bad3363f9c72f033bbf7/src/sst/elements/balar/tests/cuda-test.py.

**Comment by FDZX0118** [comment]
Thank you very much! 
I tried running SST use cuda-test.py and received an error：
“sst: symbol lookup error: /home/zhongxin/SST/GPGPUSIM/local/sstelements-12.1.0/lib/sst-elements-library/libbalar.so: undefined symbol: SST_gpgpusim_numcores_equal_check”

can you tell me how to fix it？


$ sst --model-option="-c ariel-gpu-v100.cfg

" cuda-test.py
Num args 1
0 
App args --
Configuring CPU Network-on-Chip...
Configuring CPU core 0...
Configuring GPU Network-on-Chip...
Configuring GPU core 0...
Configuring GPU core 1...
Configuring GPU core 2...
Configuring GPU core 3...
Configuring GPU core 4...
Configuring GPU core 5...
Configuring GPU core 6...
Configuring GPU core 7...
Configuring GPU core 8...
Configuring GPU core 9...
Configuring GPU core 10...
Configuring GPU core 11...
Configuring GPU core 12...
Configuring GPU core 13...
Configuring GPU core 14...
Configuring GPU core 15...
Configuring GPU core 16...
Configuring GPU core 17...
Configuring GPU core 18...
Configuring GPU core 19...
Configuring GPU core 20...
Configuring GPU core 21...
Configuring GPU core 22...
Configuring GPU core 23...
Configuring GPU core 24...
Configuring GPU core 25...
Configuring GPU core 26...
Configuring GPU core 27...
Configuring GPU core 28...
Configuring GPU core 29...
Configuring GPU core 30...
Configuring GPU core 31...
Configuring GPU core 32...
Configuring GPU core 33...
Configuring GPU core 34...
Configuring GPU core 35...
Configuring GPU core 36...
Configuring GPU core 37...
Configuring GPU core 38...
Configuring GPU core 39...
Configuring GPU core 40...
Configuring GPU core 41...
Configuring GPU core 42...
Configuring GPU core 43...
Configuring GPU core 44...
Configuring GPU core 45...
Configuring GPU core 46...
Configuring GPU core 47...
Configuring GPU core 48...
Configuring GPU core 49...
Configuring GPU core 50...
Configuring GPU core 51...
Configuring GPU core 52...
Configuring GPU core 53...
Configuring GPU core 54...
Configuring GPU core 55...
Configuring GPU core 56...
Configuring GPU core 57...
Configuring GPU core 58...
Configuring GPU core 59...
Configuring GPU core 60...
Configuring GPU core 61...
Configuring GPU core 62...
Configuring GPU core 63...
Configuring GPU core 64...
Configuring GPU core 65...
Configuring GPU core 66...
Configuring GPU core 67...
Configuring GPU core 68...
Configuring GPU core 69...
Configuring GPU core 70...
Configuring GPU core 71...
Configuring GPU core 72...
Configuring GPU core 73...
Configuring GPU core 74...
Configuring GPU core 75...
Configuring GPU core 76...
Configuring GPU core 77...
Configuring GPU core 78...
Configuring GPU core 79...
Configuring GPU core 80...
Configuring GPU core 81...
Configuring GPU core 82...
Configuring GPU core 83...
Configuring Simple mem part0 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x0 End Address: 0x3fffff800
Configuring Simple mem part1 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x100 End Address: 0x3fffff900
Creating L2 controller 0-0 (0)...
 - Start Address: 0x0 End Address: 0x3fffff800
++ 0-2 (1)...
Creating L2 controller 0-1 (1)...
 - Start Address: 0x100 End Address: 0x3fffff900
++ 1-2 (0)...
Creating L2 controller 0-2 (8)...
 - Start Address: 0x800 End Address: 0x400000000
++ 8-2 (1)...
Creating L2 controller 0-3 (9)...
 - Start Address: 0x900 End Address: 0x400000100
++ 9-2 (0)...
Creating L2 controller 0-4 (16)...
 - Start Address: 0x1000 End Address: 0x400000800
++ 16-2 (1)...
Creating L2 controller 0-5 (17)...
 - Start Address: 0x1100 End Address: 0x400000900
++ 17-2 (0)...
Creating L2 controller 0-6 (24)...
 - Start Address: 0x1800 End Address: 0x400001000
++ 24-2 (1)...
Creating L2 controller 0-7 (25)...
 - Start Address: 0x1900 End Address: 0x400001100
++ 25-2 (0)...
Configuring Simple mem part2 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x200 End Address: 0x3fffffa00
Configuring Simple mem part3 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x300 End Address: 0x3fffffb00
Creating L2 controller 1-0 (2)...
 - Start Address: 0x200 End Address: 0x3fffffa00
++ 2-2 (1)...
Creating L2 controller 1-1 (3)...
 - Start Address: 0x300 End Address: 0x3fffffb00
++ 3-2 (0)...
Creating L2 controller 1-2 (10)...
 - Start Address: 0xa00 End Address: 0x400000200
++ 10-2 (1)...
Creating L2 controller 1-3 (11)...
 - Start Address: 0xb00 End Address: 0x400000300
++ 11-2 (0)...
Creating L2 controller 1-4 (18)...
 - Start Address: 0x1200 End Address: 0x400000a00
++ 18-2 (1)...
Creating L2 controller 1-5 (19)...
 - Start Address: 0x1300 End Address: 0x400000b00
++ 19-2 (0)...
Creating L2 controller 1-6 (26)...
 - Start Address: 0x1a00 End Address: 0x400001200
++ 26-2 (1)...
Creating L2 controller 1-7 (27)...
 - Start Address: 0x1b00 End Address: 0x400001300
++ 27-2 (0)...
Configuring Simple mem part4 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x400 End Address: 0x3fffffc00
Configuring Simple mem part5 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x500 End Address: 0x3fffffd00
Creating L2 controller 2-0 (4)...
 - Start Address: 0x400 End Address: 0x3fffffc00
++ 4-2 (1)...
Creating L2 controller 2-1 (5)...
 - Start Address: 0x500 End Address: 0x3fffffd00
++ 5-2 (0)...
Creating L2 controller 2-2 (12)...
 - Start Address: 0xc00 End Address: 0x400000400
++ 12-2 (1)...
Creating L2 controller 2-3 (13)...
 - Start Address: 0xd00 End Address: 0x400000500
++ 13-2 (0)...
Creating L2 controller 2-4 (20)...
 - Start Address: 0x1400 End Address: 0x400000c00
++ 20-2 (1)...
Creating L2 controller 2-5 (21)...
 - Start Address: 0x1500 End Address: 0x400000d00
++ 21-2 (0)...
Creating L2 controller 2-6 (28)...
 - Start Address: 0x1c00 End Address: 0x400001400
++ 28-2 (1)...
Creating L2 controller 2-7 (29)...
 - Start Address: 0x1d00 End Address: 0x400001500
++ 29-2 (0)...
Configuring Simple mem part6 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x600 End Address: 0x3fffffe00
Configuring Simple mem part7 out of 4...
 - Capacity: 4294967296 per HBM
 - Start Address: 0x700 End Address: 0x3ffffff00
Creating L2 controller 3-0 (6)...
 - Start Address: 0x600 End Address: 0x3fffffe00
++ 6-2 (1)...
Creating L2 controller 3-1 (7)...
 - Start Address: 0x700 End Address: 0x3ffffff00
++ 7-2 (0)...
Creating L2 controller 3-2 (14)...
 - Start Address: 0xe00 End Address: 0x400000600
++ 14-2 (1)...
Creating L2 controller 3-3 (15)...
 - Start Address: 0xf00 End Address: 0x400000700
++ 15-2 (0)...
Creating L2 controller 3-4 (22)...
 - Start Address: 0x1600 End Address: 0x400000e00
++ 22-2 (1)...
Creating L2 controller 3-5 (23)...
 - Start Address: 0x1700 End Address: 0x400000f00
++ 23-2 (0)...
Creating L2 controller 3-6 (30)...
 - Start Address: 0x1e00 End Address: 0x400001600
++ 30-2 (1)...
Creating L2 controller 3-7 (31)...
 - Start Address: 0x1f00 End Address: 0x400001700
++ 31-2 (0)...
Completed configuring the cuda-test model
ArielComponent[arielcpu.cc:37:ArielCPU] Creating Ariel component...
ArielComponent[arielcpu.cc:43:ArielCPU] Configuring for 1 cores...
ArielComponent[arielcpu.cc:46:ArielCPU] Configuring for check addresses = no
ArielComponent[arielcpu.cc:74:ArielCPU] WARNING - ariel parameter name change: change 'memorylevels' to 'memmgr.memorylevels' in your input. The old parameter will continue to work for now but may not be supported in future releases.
ArielComponent[arielcpu.cc:80:ArielCPU] WARNING - ariel parameter name change: change 'defaultlevel' to 'memmgr.defaultlevel' in your input. The old parameter will continue to work for now but may not be supported in future releases.
ArielComponent[arielcpu.cc:100:ArielCPU] WARNING - ariel parameter name change: change 'pagecount0' to 'memmgr.pagecount0' in your input. The old parameter will continue to work for now but may not be supported in future releases.
ArielComponent[arielcpu.cc:127:ArielCPU] Loading memory manager: ariel.MemoryManagerSimple
ArielComponent[arielcpu.cc:133:ArielCPU] Memory manager construction is completed.
Pin2Frontend[frontend/simple/pin2frontend.cc:74:Pin2Frontend] Model specifies that there are 1 application arguments
Pin2Frontend[frontend/simple/pin2frontend.cc:84:Pin2Frontend] Interception and instrumentation of multi-level memory and malloc/free calls is ENABLED.
Pin2Frontend[frontend/simple/pin2frontend.cc:89:Pin2Frontend] Tracking the stack and dumping on malloc calls is DISABLED.
Pin2Frontend[frontend/simple/pin2frontend.cc:94:Pin2Frontend] Malloc map file is DISABLED
Pin2Frontend[frontend/simple/pin2frontend.cc:103:Pin2Frontend] Base pipe name: /sst_shmem_42893-0-1804289383
Pin2Frontend[frontend/simple/pin2frontend.cc:111:Pin2Frontend] Base pipe name: /sst_shmem_42893-0-846930886
Pin2Frontend[frontend/simple/pin2frontend.cc:115:Pin2Frontend] Base pipe name: /sst_shmem_42893-0-1681692777
Pin2Frontend[frontend/simple/pin2frontend.cc:127:Pin2Frontend] Processing application arguments...
Pin2Frontend[frontend/simple/pin2frontend.cc:223:Pin2Frontend] Found application argument 0 (apparg0) = --
Pin2Frontend[frontend/simple/pin2frontend.cc:257:Pin2Frontend] Completed processing application arguments.
Pin2Frontend[frontend/simple/pin2frontend.cc:262:Pin2Frontend] Completed initialization of the Ariel CPU.
ArielComponent[arielcpu.cc:169:ArielCPU] Registering ArielCPU clock at 2660MHz
ArielComponent[arielcpu.cc:173:ArielCPU] Clocks registered.
ArielComponent[arielcpu.cc:175:ArielCPU] Creating core to cache links...
ArielComponent[arielcpu.cc:177:ArielCPU] Creating processor cores and cache links...
ArielComponent[arielcpu.cc:179:ArielCPU] Configuring cores and cache links...
ArielComponent[arielcpu.cc:233:ArielCPU] Completed initialization of the Ariel RTL Link.
ArielComponent[arielcpu.cc:245:ArielCPU] Completed initialization of the Ariel CPU.
[t=0][cpu_xbar]: Creating Shogun crossbar at 800MHz clock rate and 3 ports
[t=0][cpu_xbar]: Connecting 3 links...
[t=0][cpu_xbar]: Configuring port port0 ...
[t=0][cpu_xbar]: Configuring port port1 ...
[t=0][cpu_xbar]: Configuring port port2 ...
[t=0][cpu_xbar]: Allocating pending input/output queues...
sst: symbol lookup error: /home/zhongxin/SST/GPGPUSIM/local/sstelements-12.1.0/lib/sst-elements-library/libbalar.so: undefined symbol: SST_gpgpusim_numcores_equal_check

**Comment by William-An** [comment]
You would have to source the `setup_environment` script of the `sst_gpgpusim` repo first before using balar.

**Comment by hughes-c** [comment]
@FDZX0118 sourcing the environment in sst-gpgpusim should have fixed your problem. Note that the version of balar packaged with sst-13.0 is a complete rewrite and is no longer supported with Ariel.
