### ISSUE TITLE
About merlin setting Fat-tree topology and node allocation method

### ISSUE THREAD

**Issue by sunsirui** [sstsimulator/sst-elements#2133]
Hello, 
  1. I want to know how to set the Fat-tree topology in SST-elements, is it possible to receive json file input? The purpose is to customize the Fat-tree structure and routing methods without having to follow the theoretical topology rules.
   2. There is a question about node communication. Assume that there are 8 nodes in my topology, but I want to customize the communication method of node pairs (input file settings) instead of following a fixed template.
   

Thank you very much in advance to anyone who takes the time to reply.

**Comment by feldergast** [comment]
The fat-tree topology is not configurable, other than to specify the "shape" of the topology (i.e. levels in the tree, number of up/down links at each level, routing algorithm, etc).  If you want to use a new routing algorithm, you will need to add it directly to the source files (sst/elements/merlin/topology/fattree.{h,cc}).  If you want to also change the connection structure, you will need to edit the merlin python file (sst/elements/merlin/topology/pymerlin-topo-fattree.py) to add the new connection algorithm.

**Comment by sunsirui** [comment]
Thank you
