### ISSUE TITLE
Validation of SST-Merlin Dragonfly network model (vs. booksim2)

### ISSUE THREAD

**Issue by ziyuezzy** [sstsimulator/sst-elements#2152]
New Issue for sst-elements
--------------------------

1 - Detailed description of problem or enhancement

Dear developers of SST(-Merlin), I am a researcher that is trying to use SST-Merlin.
I have been working on validating SST-Merlin's network model against Booksim2.
First of all, I tested single-router configuration and 8-by-8 Torus configuration for Booksim2 and SST-Merlin, the data between two simulators matches ok-ish if the xbar bandwidth is 64GBps in Merlin and 'internal speedup' is 2.0x in booksim. 
However, for Dally-Dragonfly, I found significant mismatch between the data produced by two simulators.

I wonder whether or not the authors of SST(-Merlin) is aware of this? Are you attempting to update Merlin in order to match with the simulation results of Booksim2, or are you validating SST-Merlin with other source?
Welcome to contact me via email ziyue.zhang@ugent.be. Also let me know if you are interested in the validating data I mentioned above.

2 - Describe how to reproduce

3 - What Operating system(s) and versions 

4 - What version of external libraries (Boost, MPI)

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by feldergast** [comment]
We have not compared the SST dragonfly model to booksim, nor do we have any plans to do so.  We did work with the CODES group and ran similar simulations on the two simulators.  We have also compared to some of our platforms in the past and some other groups have compared it to proprietary models of available products with good results.  We hope to be able to do a comparison against Slingshot when we have time and access to some of the newer systems.

I suspect the differences between SST and booksim will come down to two things: how the internal timings in the routers are modeled (at least I was told this was different with the first version of booksim, which apparently had very optimistic timings for the internal router pipeline) and the details of the adaptive routing algorithms.  What differences we found between CODES and SST also came down to these two aspects of the models. Unfortunately, I don't have time right now to dig into the details, though it would be interesting to know what is causing the differences.

**Comment by ziyuezzy** [comment]
Hi, thanks for your reply.

First of all, we have observed significant mismatch with 'min' routing algorithm already, so the difference of adaptive algorithm implementation can pass for now. 
I also suspect that the difference between Booksim and Merlin is due to the different router models (Although I am only familiar with Booksim2 instead of Booksim1). In Booksim2, their default router is an 'iqrouter' with 'Rouitng/Queuing -> VC allocation -> Switch allocation -> Crossbar Traversal' intra-router pipeline. In comparison, the hr_router model in Merlin is relatively simplistic, I think. 
I am not saying that Booksim2's router model is the Bible, so but if you have implemented 'hr_router' in Merlin according to another micro-architecture, it will make sense that they don't behave similarly. So I wonder what was the theoretical base that you have followed to implement the 'hr_router' in Merlin? Is there patent or publication? 

Thanks for your time.

**Comment by feldergast** [comment]
The hr_router implementation was meant to be a generic high-level model of an input-output queued switch.  It is intentionally not based on any existing specific architecture.  It approximates internal load-free latency by pushing the latency onto the input and output links.  This is designed to approximate the time for the internal pipeline, including functions like routing, VC selection and arbitration time.  In addition to the base latency, it will also model queueing latency, waiting for crossbar arbitration and waiting for output arbitration.  It also models contention of all the resources, including input and output queues and the available crossbar bandwidth.  The flow of a packet through the router is:

1 - input queue
2 - routing and VC allocation once a packet reaches the head of the input queue
3 - crossbar arbitration
4 - crossbar traversal (this adds no latency, but does account for bandwidth utilization blocking other packets until the current packet is done)
5 - output queue
6 - output arbitration among the VCs

The base latencies of 1 - 3 are accounted for by the input latency set on the router and the base latencies of 4-6 are accounted for by the output latency.  Accounting for the independent latencies would likely change the behavior somewhat, but I wouldn't expect it to be a major difference.

A couple other thing worth noting for hr_router:
- It doesn't interleave flits from different packets.  For simulator efficiency reasons, merlin only tracks packets and not individual flits (other than to tie up resources long enough to account for all the flits in the packet).  However, I would only expect this to make a difference if you were simulating communication patterns with both large and small packets.
- It really only tracks the head of the packet as far as latency goes.  If the endpoint wants the total latency, it will need to account for the serialization delay of the packet.

By iqrouter, do you mean the router is only input queued and a packet that traverses the crossbar is immediately sent to the next router?  If so, that would definitely affect the behavior compared to an input/output queued router.

**Comment by ziyuezzy** [comment]
Yes, the 'iqrouter' in booksim2 indeed is only input queued. The flow control is only between the virtual channels that are in the input buffers of two connected iqrouters. 
I tried to do some tricks to implement the idea of only input-queueing in Merlin's hr_router, but it did not mitigate the simulation result difference. (But the tricks I did was probably bad practices, and did not actually simulate an iqrouter.) Moreover, I think the VC allocation mechanisms are also different from Merlin and Booksim. 
So I am not entirely sure what exactly caused the difference, but I am still trying to investigate.

**Comment by ziyuezzy** [comment]
Some updates on this work:
We have found out that the router model of Merlin matches well with booksim when "speculative switch allocation"  is enabled in booksim2. We have tested single-router, dragonfly, and torus topology with uniform traffic, the network simulation behavior matches well between booksim2 and SST-Merlin.
