### ISSUE TITLE
[Balar] How kernel acknowledges host CPU/MMIO when the kernel finish?

### ISSUE THREAD

**Issue by Yfeng-44** [sstsimulator/sst-elements#2154]
Hi all, 

According to the code comments, https://github.com/sstsimulator/sst-elements/blob/6bcddc7db8b831c7887e9794c8042e06f7d3645c/src/sst/elements/balar/balarMMIO.cc#L379 , the kernel launch and memory cpy are set to block. I'm aware that the memory copy is acknowledged by callbacks, but how are kernel launch is handled and acknowledge the host CPU and/or MMIO?

best,
Yuan

**Comment by hughes-c** [comment]
We don't support balar+host at the moment, it's coming sometime this year.
