### ISSUE TITLE
Simplify FESimple for Ariel

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#217]

**Comment by hughes-c** [comment]
@nmhamster @gvoskuilen Is this the same as https://github.com/sstsimulator/sst-elements/issues/1296?

**Comment by gvoskuilen** [comment]
@hughes-c I think this is a separate issue, relating to simplifying fesimple itself (not Ariel) and moving a lot of the dependency-specific support elsewhere.
