### ISSUE TITLE
memHierarchy backend for Cramsim 

### ISSUE THREAD

**Issue by dmukherj09** [sstsimulator/sst-elements#2180]
Hi can someone tell me how to use the memhierarchy cramsim backend in a system?
I'm using "memHierarchy.cramsim" instead of "memHierarchy,simpleMem", but it is throwing error.

Do I have to do/add something else, please let me know

**Comment by hughes-c** [comment]
Have you tried running the cramsim test?
memHierarchy/test/testBackendCramSim.py

**Comment by plavin** [comment]
When using CramSim as a backend for memHierarchy, the memory references that go into CramSim don't come from a trace file but from the simulator, so you only need a trace for Prospero.

**Comment by dmukherj09** [comment]
Yes, I resolved my issue on this now, thank you
