### ISSUE TITLE
Question on Tricount Motif

### ISSUE THREAD

**Issue by AKKamath** [sstsimulator/sst-elements#2181]
I noticed that the documentation for Tricount mentioned that it was a replica of the SHAD/GMT implementation of Triangle Counting. 

From my understanding of the motif, it assumes that the input graph is undirected while the SHAD/GMT implementation is based on any type of graph, directed or undirected. 

I was wondering whether this difference was intentional, or if this is a bug.

**Comment by jpkenny** [comment]
Are you referring to the appearance of
```
 if (src > dst) std::swap(src, dst);
```
in embertricount_setup?

If so, that is taken straight from the SHAD reference implementation.
As far as I know the motif replicates the SHAD code.
I agree the above swap would make for a strange directed graph.

**Comment by AKKamath** [comment]
Yeah, that's what I was curious about. Thanks for the response!
