### ISSUE TITLE
Python 3.12 fixes required

### ISSUE THREAD

**Issue by jmlapre** [sstsimulator/sst-elements#2339]
Python 3.12 changed how they handle regular expressions.
Invalid escape sequences generate a SyntaxWarning instead of a DeprecationWarning.

https://docs.python.org/3/whatsnew/3.12.html#other-language-changes

**Comment by jmlapre** [comment]
Related to https://github.com/sstsimulator/sst-core/issues/1002

**Comment by berquist** [comment]
Fixed in https://github.com/sstsimulator/sst-core/pull/1073 and https://github.com/sstsimulator/sst-elements/pull/2351
