### ISSUE TITLE
Dynamic linking of libotf2.so is broken

### ISSUE THREAD

**Issue by freund** [sstsimulator/sst-elements#2390]
New issue for sst-element
----------------------
1. _Detailed description of problem_
Compiling with OTF2 support works, but trying to actually use OTF2 (via the Ember OTF2 motif) results in `sst: symbol lookup error: libember.so: undefined symbol: OTF2_Reader_Open` because of an issue with the dynamic linking to libotf2.so. There is a workaround: run SST with the `LD_PRELOAD` environment variable set to the path of libotf2.so.

2. _Describe how to reproduce the issue_
Compile with OTF2 support and use the Ember OTF2 motif to read a trace with `addMotif("OTF2 tracePrefix=traces.otf2")`.

4. _What operating system and versions_
TOSS 4.8-2.

6. _What versions of external libraries (MPI, etc.)_
otf2 3.0.3

8. _Provide sha1 of all relevant SST repositories (sst-core, sst-elements, etc.)_
`sst-core c13aff968e9684ceab0f2b50e0887c08091956cd`
`sst-elements 2664955f14ed0ce7d9b0c77d3a18436df5a2c72b`

**Comment by jwilso** [comment]
Fixed in #2392.
