### ISSUE TITLE
Ember OTF2 motif hangs when attempting to replay a Bcast

### ISSUE THREAD

**Issue by freund** [sstsimulator/sst-elements#2391]
New issue for sst-element
----------------------
1. _Detailed description of problem_
Trying to use the Ember OTF2 motif to replay a trace containing an MPI_Bcast will cause the simulation to hang. The motif loads the trace successfully, but then the simulation never completes.

2. _Describe how to reproduce the issue_
Generate the trace of an MPI application containing a Bcast. Then compile sst-elements with OTF2 support and use the Ember OTF2 motif to read that trace with `addMotif("OTF2 tracePrefix=traces.otf2")`.

4. _What operating system and versions_
TOSS 4.8-2.

6. _What versions of external libraries (MPI, etc.)_
otf2 3.0.3
openmpi 4.1.2

8. _Provide sha1 of all relevant SST repositories (sst-core, sst-elements, etc.)_
`sst-core c13aff968e9684ceab0f2b50e0887c08091956cd`
`sst-elements 2664955f14ed0ce7d9b0c77d3a18436df5a2c72b`

**Comment by jwilso** [comment]
Closed in #2392
