### ISSUE TITLE
Motif: AllPingPong

### ISSUE THREAD

**Issue by h4u5** [sstsimulator/sst-elements#243]
The AllPingPong motif hangs when a topology with an odd number of ranks is passed in.
It seems like this is just a rank that doesn't have a partner to ping pong with.

I attached a proposed fix
[emberallpingpong.cc.txt](https://github.com/sstsimulator/sst-elements/files/226131/emberallpingpong.cc.txt)

**Comment by nmhamster** [comment]
I added a fix for this in PR #291. Will close the issue, please re-open if this doesn't fit it.

**Comment by nmhamster** [comment]
I added a fix for this in PR #291. Will close the issue, please re-open if this doesn't fit it.
