### ISSUE TITLE
Motif: Alltoall hanging

### ISSUE THREAD

**Issue by h4u5** [sstsimulator/sst-elements#244]
I haven't looked into it in detail yet, but running with these parameters seems to hang until it runs out of time (> 10 hours on 64 nodes of Chama).

EMBER: network: topology=dragonfly2 shape=49:49:1:49 arbitration=xbar_arb_lru
EMBER: numNodes=117649 numNics=117649
EMBER: network: BW=12.5GB/s pktSize=2048B flitSize=32B
EMBER: Job: -nidList=0-117648 -ranksPerNode=1 ['Init']
EMBER: Job: -nidList=0-117648 -ranksPerNode=1 ['Alltoall', 'bytes=1', 'iterations=1', 'compute=1']
EMBER: Job: -nidList=0-117648 -ranksPerNode=1 ['Fini']

**Comment by nmhamster** [comment]
This has been fixed in several updates to Merlin, Ember and FireFly.
