### ISSUE TITLE
Dragonfly global link arrangements in merlin

### ISSUE THREAD

**Issue by fkaplan3** [sstsimulator/sst-elements#266]
Currently dragonfly supports 'absolute arrangement' as the global link arrangement. It should support other arrangements through a user defined 'global link map'.
The initial infrastructure to build upon is created under 'dragonfly2' and it currently is set to use a default global link map.

**Comment by feldergast** [comment]
Have not yet been able to reproduce this error with identical network, but using merlin::test_nic.  Will need to look into it more using ember endpoints.
