### ISSUE TITLE
Trac: #371 Large abnormal latencies between LLC and DC

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#28]
Large latencies in the order of 150-350 cycles are seen in the route between the last level caches and directory controller. The problem has come to light with a VaultSim backend configuration whose bandwidth is 5x larger than is reported, and doesnt appear to be the bottleneck. The LLCs are connected by a Merlin router which doesnt appear to contain many crossbar or port stalls. Such large latencies are not to be expected.

**Comment by gvoskuilen** [comment]
Closing because this is no longer observed.
