### ISSUE TITLE
Ember: random placement of ranks doesn't scale

### ISSUE THREAD

**Issue by h4u5** [sstsimulator/sst-elements#294]
Running jobs simulating 100k nodes that normally take 30 minutes fail to complete in 4 hours after random placement is enabled.

**Comment by nmhamster** [comment]
This is likely to be a product of greater simulation requirements since the traffic may now need to travel further and is likely to cause greater levels of congestion in the models. We will need to check this on subsequent modifications to devel branch but its not clear its really a bug yet.
