### ISSUE TITLE
.ignore feature on autogen.sh is missing

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-elements#302]
After move to external elements. the .ignore feature of the autogen.sh is now missing.

**Comment by nmhamster** [comment]
I am hoping to remove this feature due to our new development workflow on Github meaning we shouldn't ever get into a situation where this is really needed. Is this a bad design thought?

**Comment by allevin** [comment]
I agree that we don't need it, but some people who used in the past may still be expecting it.  This issue notes that the feature was removed.  

However, I would like to get other opinions before we abandon it completely.

**Comment by allevin** [comment]
Feature re-added in PR #351
