### ISSUE TITLE
Zoltan test with 8 ranks has a rank with a large imbalance

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#336]
This was evident but un-noted until the recent ember enhancements.  The old partitioning on 8 ranks was:

```
         Per Cent
```

Rank0  16    12.50   (Good)
Rank1  16    12.50   (Good)
Rank2  16    12.50   (Good)
Rank3  16    12.50   (Good)
Rank4  22    17.18   (Working but lousy)
Rank5  10    7.81   (Working but lousy)
Rank6  18    14.06   (Working but lousy)
Rank7  14    10.93   (Working but lousy)

With the ember rearrangement, rank 4 gets significantly more unbalanced.

It is believed that the issue is that the weights have not been appropriately readjusted for no-cut specifications.

Zoltan test 8 has been temporarily turned off in the the nightly and autotester tests.

**Comment by nmhamster** [comment]
@jpvandy is Zoltan testing still disabled for mainline SST?
