### ISSUE TITLE
Merlin gives fatal with new global link arrangements in Dragonfly

### ISSUE THREAD

**Issue by fkaplan3** [sstsimulator/sst-elements#337]
Merlin gives a fatal error when using the new (relative) global link arrangements in dragonfly2 network:
[bungee13:07134] **\* Process received signal ***
[bungee13:07134] Signal: Segmentation fault (11)
[bungee13:07134] Signal code: Address not mapped (1)
[bungee13:07134] Failing at address: 0x8
[bungee13:07134] [ 0] /lib64/libpthread.so.0(+0xf7e0)[0x2b4db64407e0]
[bungee13:07134] [ 1] /mnt/nokrb/fkaplan3/SST/local/sst-elements/lib/sst-elements-library/libmerlin.so(_ZN3SST6Merlin11PortControl4sendEPNS0_21internal_router_eventEi+0x5f)[0x2b4dc404041f]
[bungee13:07134] [ 2] /mnt/nokrb/fkaplan3/SST/local/sst-elements/lib/sst-elements-library/libmerlin.so(_ZN3SST6Merlin9hr_router13clock_handlerEm+0x107)[0x2b4dc405af77]
[bungee13:07134] [ 3] sst(_ZN3SST5Clock7executeEv+0xe6)[0x5e1476]
[bungee13:07134] [ 4] sst(_ZN3SST10Simulation3runEv+0x19f)[0x6574cf]
[bungee13:07134] [ 5] sst[0x5b3e60]
[bungee13:07134] [ 6] sst(main+0x218c)[0x5dc73c]
[bungee13:07134] [ 7] /lib64/libc.so.6(__libc_start_main+0xfd)[0x2b4db7e80d5d]
[bungee13:07134] [ 8] sst[0x5b2f69]
[bungee13:07134] **\* End of error message ***

Error can be reproduced by using the following configurations:
(1) dragonfly2 network with 17 groups (--topo=dragonfly2 --shape=2:4:1:17 --numCores=2)
(2) relative global link mode ON (setGlobalRouteModeRelative())
(3) ember+merlin simulation
(4) alltoall motif which uses all 136 nodes

**Comment by allevin** [comment]
@feldergast to investigate
