### ISSUE TITLE
Trac: #381 Less counter intuitive variable names in loadInfo.py

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#34]
In sstelementsembertestloadInfo.py (around line 100) 

In function initWork, each work contained in list workList is enumerated and passed to function readWorkList 

In that function, the work is renamed workList and in another for loop, each work of this workList (previously work) is processed. 

These multiple work, worklist, workflow, etc. makes loadInfo.py extremely hard to read. Perhaps other variable names could be employed 

Also, for what does nidList stand for And what if the different work contained in the worklist as defined in function readWorkList define through their cmd different nidList Same question for ranksPerNode

**Comment by allevin** [comment]
@feldergast will address.

**Comment by hughes-c** [comment]
Won't fix.
