### ISSUE TITLE
Configuration summary doesn't show correct result for goblin hmcsim

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-elements#357]
When I configure the elements with '--goblin-hmcsim=', the configure shows it finds goblin:
checking hmc_sim.h usability... yes
checking hmc_sim.h presence... yes
checking for hmc_sim.h... yes
checking for hmcsim_clock in -lhmcsim... yes
checking for GOBLIN HMC Simulator library... yes

but in the printout of 'Configuration Information (Dependencies):', it shows:
goblin_hmcsim : No

This should report 'Yes'.

**Comment by nmhamster** [comment]
@gvoskuilen you using GOBLINSim 1 or 2? I think this bug stands but I want to catalog which ones we know work as well. Thanks.

**Comment by allevin** [comment]
The actual problem was introduced by the new configuration reporting changes.  The problem has been identified and corrected in PR #358.

**Comment by gvoskuilen** [comment]
I was using GOBLINSim 2. I'm closing this since the bug is fixed.
