### ISSUE TITLE
scheduler requires boost_thread, but does not check for it

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-elements#368]
On a system without libboost-thread installed, 'scheduler' will pass ./configure, but will fail to build due to the missing dependency.

**Comment by vjleung** [comment]
Aaron,

Scheduler may not actually require boost_thread, so there are two ways we can go with this.  We can add the check for it, or we can see about removing the requirement.

Vitus

**Comment by nmhamster** [comment]
Issue fixed in latest Boost overhaul.
