### ISSUE TITLE
Trac: #425 Problem in UniformDist (trafficgen)

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#38]
When the generator is re-seeded (trafficgen.h:157) a new Mersenne RNG stream is created but this stream is not redirected to the SSTUniformDistribution, so the original seed is kept.

I fixed that this way: 

```
void seed(uint32_t val) 
{
    gen = new MersenneRNG((unsigned int) val); 
    dist->setGenerator(gen); 
} 
```

and added a new function setGenerator in SSTUniformDist

**Comment by jwilso** [comment]
@afrodri:  @nmhamster please review for closure.

**Comment by nmhamster** [comment]
New seed procedures in place to address this issue.
