### ISSUE TITLE
PR_SET_PTRACER not checked for in config, fails on certain ariel builds

### ISSUE THREAD

**Issue by afrodri** [sstsimulator/sst-elements#405]
New Issue for sst-elements

`1` Detailed description of problem or enhancement
arielcpu.cc:461:31: error: ‘PR_SET_PTRACER’ was not declared in this scope
                         prctl(PR_SET_PTRACER, getppid(), 0, 0 ,0);
THe PR_SET_PTRACER flag was added in Linux 3.4, so this line will fail on older systems. 

What is the prctl call used for in this case?

`2` Describe how to reproduce
Compilation on Linux<3.4 should fail (e.g. shepard.sandia.gov)

`5` Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

`6` Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by nmhamster** [comment]
Fixed in #406 and merged into the `devel` branch.
