### ISSUE TITLE
Trac: #443 CHDL component is not ready for release.

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#41]
Previous issue #329. It will not build with gcc-4.4.7 because of C++11 usage - this is probably not to get fixed. (Nightly testing is disabled if C++11 is not available.) 

Current version of chdl will not build with Clang compiler. Appears to be fine with gcc-4.7 and gcc-4.8.1. The log of a Clang compile failure is attached. (Nightly testing is disabled on Clang compilers.) 

The test needs two input files which are being fetched from kersey.com, which need to be install in sst downloads. 

The external component for chdl comes from three git downloads which are not from a release but from a HEAD of a repository.

**Comment by allevin** [comment]
Log of CHDL external build failure

**Comment by allevin** [comment]
gcc-4.4.7 support is a still a requirement for SST 5.1.0. (move this issue to Milestone 6.0)

**Comment by allevin** [comment]
[CHDL.vs.Clang.txt](https://github.com/sstsimulator/sst-elements/files/10235/CHDL.vs.Clang.txt)
