### ISSUE TITLE
Potential Memory Leak in Large Simulations where Prefetching with Cassini is Enabled

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#411]
See seg-fault because run out of memory when running large SNB style simulations with StridePrefetcher enabled.

**Comment by gvoskuilen** [comment]
Confirmed with the following configs:
Devel branches of elements & core.
SNB w/ Ariel & DRAMsim or GoblinHMC backend.
SNAP with 1G or 8G memory footprint; PENNANT with 1G footprint.

SST's memory use grows as soon as ariel_enable is hit. Eventually, the app gets a sigkill and dies. SST continues until it's killed manually. Turning off the prefetchers eliminates the problem. The NextBlock prefetcher is ok, so the problem appears to be in the stride prefetcher itself.

**Comment by gvoskuilen** [comment]
Fixed in PR #420
