### ISSUE TITLE
Ariel doesn't detect when the app its running becomes a zombie

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-elements#418]
When Ariel's child process becomes a zombie (e.g., due to a sigkill), Ariel doesn't check and continues running. Instead, if Ariel hasn't received requests for some amount of time, it should poll the child to check if it's still active. If not, it should end the simulation with an error.

**Comment by nmhamster** [comment]
Moving to SST v6.1.0. There is something of a start on this in the current version of the code but it does not work everywhere etc yet.

**Comment by gvoskuilen** [comment]
Closing for now - changes were made to prevent the child process from persisting when Ariel exits and we haven't seen this issue much recently.
