### ISSUE TITLE
Compilation fails on Archlinux: scheduler missing include

### ISSUE THREAD

**Issue by luisfnqoliveira** [sstsimulator/sst-elements#424]
I get a compilation error on Archlinux (and other related errors):
`DragonflyMachine.cc:122:78: error: ‘ceil’ was not declared in this scope`

on the following file:
`sst-elements/src/sst/elements/scheduler/DragonflyMachine.cc`
`sst-elements/src/sst/elements/scheduler/StencilMachine.cc`
`sst-elements/src/sst/elements/scheduler/Torus3DMachine.cc`

The fix is easy, in those files add:
`#include <cmath>`

This error does not occur in Ubuntu 14.04.

OS: Archlinux
GCC:6.1.1
Boost:1.56.0
OpenMPI:1.8
SST-Core commit: eb8280abb3d535dff3813f909d0b8bc67010669a
SST-Elements commit: 5c0e78b0510b273c9cfcfd078b0e43e0a524caf1

**Comment by allevin** [comment]
This issue was corrected with PR #425
