### ISSUE TITLE
Stats warning could be slightly more helpful 

### ISSUE THREAD

**Issue by cdunham** [sstsimulator/sst-elements#433]
https://github.com/sstsimulator/sst-elements/search?q=Please+see+sstinfo

The executable appears to be "sst-info"

**Comment by allevin** [comment]
Curtis,

Can you provide a better description of the problem?  Is this an issue with the Statistics engine in the core?  Is is a problem with sst-info?  or is it a problem with MemHierarchy?

What is the problem with the warning, and what do you suggest as a possible solution?

**Comment by cdunham** [comment]
Simply s/sstinfo/sst-info/ the messages as that seems to be the name of the
tool when built from sst 6.0 tarballs.

**Comment by nmhamster** [comment]
@allevin @gvoskuilen see PR #434 for fix.

**Comment by allevin** [comment]
Not enough information to resolve this issue.  PR#434 shows an attempted fix.
