### ISSUE TITLE
Trac: #470 Ariel test failures/time-limits leave behind allocated shared memory Segments.

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#46]
After we run out of resources:
/home/jpvandy/CentOS-bamboo-Sep10_0820/devel/trunk/sst/elements/ariel/frontend/simple/examples/stream/runstreamNB.py
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'

what(): Permission denied

[sst-test:11556] **Process received signal**
[sst-test:11556] Signal: Aborted (6)
[sst-test:11556] Signal code: (-6)
[sst-test:11556] [ 0] /lib64/libpthread.so.0[0x30a580f710]
[sst-test:11556] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x30a5432625]
[sst-test:11556] [ 2] /lib64/libc.so.6(abort+0x175)[0x30a5433e05]
[sst-test:11556] [ 3] /usr/local/module-pkgs/gcc/4.6.4/lib64/libstdc++.so.6(_ZN9gnu_cxx27verbose_terminate_handlerEv+0x11d)[0x7fe58a6c934d]
[sst-test:11556] [ 4] /usr/local/module-pkgs/gcc/4.6.4/lib64/libstdc++.so.6(+0xb74f6)[0x7fe58a6c74f6]
[sst-test:11556] [ 5] /usr/local/module-pkgs/gcc/4.6.4/lib64/libstdc++.so.6(+0xb7523)[0x7fe58a6c7523]
[sst-test:11556] [ 6] /usr/local/module-pkgs/gcc/4.6.4/lib64/libstdc++.so.6(cxa_rethrow+0x46)[0x7fe58a6c7666]
[sst-test:11556] [ 7] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/lib/sst/libariel.so(_ZN3SST4Core12Interprocess9IPCTunnelINS_14ArielComponent15ArielSharedDataENS3_12ArielCommandEEC2ERKSsmm+0xa5b)[0x7fe584883e6b]
[sst-test:11556] [ 8] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/lib/sst/libariel.so(_ZN3SST14ArielComponent8ArielCPUC1EmRNS_6ParamsE+0x1461)[0x7fe584876e51]
[sst-test:11556] [ 9] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/lib/sst/libariel.so(+0x19024)[0x7fe584873024]
[sst-test:11556] [10] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/bin/sst(_ZN3SST7Factory15CreateComponentEmSsRNS_6ParamsE+0x459)[0x63dc39]
[sst-test:11556] [11] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/bin/sst(_ZN3SST10Simulation13performWireUpERNS_11ConfigGraphEim+0xf6e)[0x67ea7e]
[sst-test:11556] [12] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/bin/sst(main+0x2899)[0x5df3e9]
[sst-test:11556] [13] /lib64/libc.so.6(libc_start_main+0xfd)[0x30a541ed5d]
[sst-test:11556] [14] /home/jpvandy/CentOS-bamboo-Sep10_0820/local/bin/sst[0x5be6f1]
[sst-test:11556] **End of error message**
/home/jpvandy/CentOS-bamboo-Sep10_0820/devel/trunk/test/testSuites/testSuite_Ariel.sh: line 74: 11556 Aborted

**Comment by allevin** [comment]
The testing infrastructure should probably remove any stale resources that remain if it kills SST without giving it a chance to clean up after itself. The ipcs and ipcrm commands are of interest here.
