### ISSUE TITLE
CramSim needs more input checking

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#465]
With the command line,
sst tests/test_txntrace4.py --model-options="--configfile=ddr4_verimem.cfg --tracefile=tests/sst-CramSim-trace_verimem_1_R.trc",
if the tracefile is misspelled, the test runs happily, reporting a simulation time 110 us and 0 for all the statistic.
It would be more appropriate if the "--tracefile=" is declared but none found, to report an error.
@tejaskarkhanis

**Comment by mbhealy** [comment]
This issue has been resolved with the latest merge to devel.
