### ISSUE TITLE
MemHSieve encounters occasional Time Limits

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#466]
This is not a frequent, nor a reproducible-on-demand issue.   It seen primarily on MacOS, perhaps exclusively.    These time limits were the trigger for the time limit hangs reported in SQE issue #342.  (The time limits have been contained.)   (The memHSieve test is clean on Valgrind on Linux.) 
@gvoskuilen

**Comment by jpvandy** [comment]
Another just occurred on the anytester El Capitan Project.

**Comment by gvoskuilen** [comment]
Moving this to issue #674
