### ISSUE TITLE
CramSim tests have occasional output problems

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#467]
This is not a solid failure. The manifestion is one or more output lines mixed with each other.  It is seen less than once per execution of the 11 test Suite and has only been observed in the multi-thread sst-option..  It is not the same test each time.

A sample output discrepancy is 

! CramSim_6_W test Fails
! shunit.ASSERT: outFile word/line count does NOT matches Reference
! 5,6d4
! < Deleting DIMM
! < Refresh's sent out: 0
! 11c9,11
! < Total Txns Received: 24776
! ---
! > Deleting DIMMTotal Txns Received: 24776
! > 
! > Refresh's sent out: 0

**Comment by jpvandy** [comment]
The CramSim testing criterion was significantly reduce to ignore the wrongly printed output when running multithread.   It is believed that the calculation is correct only the printed output is wrong.

**Comment by gvoskuilen** [comment]
Addressed in #1545
