### ISSUE TITLE
Simulation configuration file with Ariel and memHierarchy

### ISSUE THREAD

**Issue by dhiraj113** [sstsimulator/sst-elements#469]
Is there an example simulation configuration file (sdl.py) with the components ariel and memHierarchy connected together? 

I haven't found even a single configuration file with ariel and memHierarchy components connected. Also, in general, what is the best approach for figuring out how to write configuration files for connecting various components?

**Comment by gvoskuilen** [comment]
There's a couple places you can look. On the sst-simulator.org site, if you go to Downloads, and find the "tutorials" section, there are examples for connecting both Ariel & Miranda to memHierarchy in "Building a Simulator Examples". The other place you can look is in src/sst/elements/ariel/frontend/simple/examples/stream/.

**Comment by nmhamster** [comment]
@dhiraj113 do you have what you need for your question? If so, we can close the issue. If you don't let us know so we can help some more. Thanks!

**Comment by dhiraj113** [comment]
I have been using the ariel_snb.py configuration file. It solves my requirements for now. So, I am closing the issue. Thanks.
