### ISSUE TITLE
sst-info documentation for FFT-3D iterations needs update

### ISSUE THREAD

**Issue by h4u5** [sstsimulator/sst-elements#578]
Easy fix, it currently says,

SUBCOMPONENT 5 = FFT3DMotif (Models an FFT)
         NUM PARAMETERS = 12
            PARAMETER 0 = arg.iterations (Sets the number of ping pong operations to perform) [1]

replace "ping pong operations" with FFTs

**Comment by allevin** [comment]
sst-info just reads the element info data and reports it.  The issue is the element info data for the FFT3DMotif subcomponent.  This data needs to be updated.

**Comment by nmhamster** [comment]
Fixed in PR #1541.
