### ISSUE TITLE
Trac: #159 Merlin autoconfiguration

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#6]
Merlin should be capable of autodiscovery of unset network parameters, assuming the parameters are set elsewhere in the system.

**Comment by allevin** [comment]
While Merlin now does some auto-discovery, the remainder will be pushed back to 4.1.

Some of this added in 4.1.0, some more features will be added in 5.0.0

**Comment by feldergast** [comment]
No new features added for 6.0.  New features will include auto sizing of input buffers, but this requires functionality that is not yet in the core.  Changing milestone to 7.0.

**Comment by nmhamster** [comment]
Autoconfiguration now mostly added. Closing this issue, re-open if needed.
