### ISSUE TITLE
Typo in ember test file

### ISSUE THREAD

**Issue by shavvn** [sstsimulator/sst-elements#62]
Hi there,

There's a typo in **elements/ember/test/emberLoad.py** , line 65:

````
except getopt.GetopError as err
````

should be

````
except getopt.GetoptError as err
````

I was passing a wrong option and it broke, I stared at the line for a while and wondered why it would break (I thought it was the interpreter missing something) then I realize there's a "t" missing lol

Thanks,
Shang

**Comment by nmhamster** [comment]
Hey Shang, thanks for the bug report! Merged in pull request #63.
