### ISSUE TITLE
Merlin Dragonfly Question

### ISSUE THREAD

**Issue by shavvn** [sstsimulator/sst-elements#64]
Hi I was playing with merlin and trying to build a dragonfly network. In the /merlin/topology/dragonfly.cc source code I found (line 215):

```
uint32_t topo_dragonfly::router_to_group(uint32_t group) const
{
    /* For now, assume only 1 connection to each group */
```

Does it mean I cannot have more than 1 inter-group link per router?

Thanks,
Shang

**Comment by feldergast** [comment]
That is currently correct.  I'm working this week on removing that constraint.

Scott

**Comment by shavvn** [comment]
great  good to know that! thanks!

**Comment by nmhamster** [comment]
Scott, I think you have fixed this now correct?

**Comment by nmhamster** [comment]
This is confirmed fixed in recent additions from @feldergast. Closing issue. Code is now in the devel branch.
