### ISSUE TITLE
Valgrind finds issues with Samba

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#650]
Samba was recently added to nightly Valgrind testing.

Valgrind identifies 4 issues in each of the Samba tests.

(Except for HybridSim the rest of the SST tests run clean with respect to Valgrind.)

Attached is the file from one of the tests:
[test_Samba_streambench_mmu.VGout.txt](https://github.com/sstsimulator/sst-elements/files/965564/test_Samba_streambench_mmu.VGout.txt)

**Comment by amroawad2** [comment]
Soved
