### ISSUE TITLE
Run a real MPI application code or an MPI trace using sst 

### ISSUE THREAD

**Issue by skaramati** [sstsimulator/sst-elements#669]
I am wondering if there is any tutorial to help me run a real MPI application code or an MPI trace using sst.

Thanks

**Comment by jjwilke** [comment]
Hi,

Thanks for your interest in SST.

Depending on your exact use case, you'll most likely want to use sst-macro, possibly Ember. Have a look a the sst-macro repository and the PDF manual contained there. 

For questions, you can contact us at sst-macro-help@sandia.gov.  If you have some more details about your use case, send us a note there and we'll work with you to get going.

We usually use the issue tracker for bug reports and the mailing list for user questions.
