### ISSUE TITLE
Merlin Topologies

### ISSUE THREAD

**Issue by Christian9212** [sstsimulator/sst-elements#680]
Detailed description of problem or enhancement
Hi everyone, i have recently installed SST, and i am strugling a bit with "know-how"/"tutorials"/"guidelines" regarding network topologies, and full-system simulation. I can barely find any examples out there. What i really need right now is an Fat-tree network topology, but dont know exactly how to do it. Even so, i am still trying and learning to use the SST.

Any relevant info please? And sorry for any mistakes, but i'm new to SST and i would like to use it.

 What Operating system(s) and versions 
Linux-Ubuntu 16

Thx

**Comment by nmhamster** [comment]
Hi @Christian9212 - here is a response from one of our developers on this question recently.

>    The simplest way to generate a topology (including Fat Tree) with Merlin is to use the built-in topology generators. Manually setting up something like a large fattree network is definitely error prone (but not impossible).
>  
>   Please have a look at https://github.com/sstsimulator/sst-elements/blob/devel/src/sst/elements/merlin/networkGen.py
>  
>    It gives you the option of choosing your topology, and your endpoint type, and prompts you to supply the configuration parameters that you want to use for the simulation.

Let us know if this helps you get started or if you need any additional information. Thanks for your interest in SST!

**Comment by allevin** [comment]
No response from author, considering this issue closed
