### ISSUE TITLE
Is there a way to get Clock cycle count per instruction type for Ariel?

### ISSUE THREAD

**Issue by yeungsl** [sstsimulator/sst-elements#689]
New Issue for sst-elements
--------------------------

In the Statistic output of Ariel I can only find number of instructions ran by the CPU and some TLB stats. But I would like to have some clock cycle count statistics from the simulation so that I can calculate CPI for the program I ran. Is there any way of printing the clock cycle out?

**Comment by nmhamster** [comment]
@yeungsl - the current version of the develop branch for SST has this statistic included. It is not in the 7.1 version of the code.

**Comment by yeungsl** [comment]
Its on devel branch right? Thanks I will try to build that one.

**Comment by nmhamster** [comment]
@yeungsl - yes. We have not done any extensive evaluation on the counter yet but we added the code because you had indicated you needed it in another post. It should count cycles for whenever Ariel is active.

**Comment by yeungsl** [comment]
Thanks, but I cannot compile it since I did not see any Configure (the executable) in the repo. I copied the source into the tar file you guys released online and ran Configure, but it complains there is no Makefile.in, should I copy all the Makefile.in into all the directory also?

**Comment by yeungsl** [comment]
Problem solved. I just added the code you guys changed on the branch into the source . Everything works fine. Thank you very much
