### ISSUE TITLE
Prospero PIN Tool Test Fails because of GLIBC 32-bit Library Issue

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#73]
Fails to correctly load glibc during profiling.

**Comment by nmhamster** [comment]
@jpvandy is this still failing on multiple platforms now? I think the recent modification to the Prospero build system are ensuring that this works as planned?

**Comment by jpvandy** [comment]
I believe we still are NOT runing prospero,pin test on any platform.

I believe that if the build of prospero pin now works we are not testing it anywhere.

**Comment by nmhamster** [comment]
@jpvandy is this something we can enable? I /think/ the new build process will make Prospero work if we use the new tool to generate traces. This is something we can do when you're back (no rush).
