### ISSUE TITLE
CHDL Fails with SST Threaded Core

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#75]
Fails with n > 1

**Comment by nmhamster** [comment]
@cdkersey any update on whether CHDL should be working with the SST Threaded PDES core? Thank you.

**Comment by cdkersey** [comment]
It is still expected not to work. I have a replacement for the CHDL
component which should be thread-safe, but I haven't tried to test it with
the threaded core yet. I'll do that and make a pull request ASAP.

-chad

**Comment by allevin** [comment]
CHDL is now in the archive.  This issue is closed.
