### ISSUE TITLE
McOpteron Does Not Have Reproducible Results

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#76]
Output is one of two answers, not reproducible output on Mac OSX.

**Comment by nmhamster** [comment]
Jeanine will take a look and fix prior to SST v6.0 release.

**Comment by jpvandy** [comment]
McOpteron is also not compatible with PDES core.    Test1 goes time limit for n > 1

**Comment by jpvandy** [comment]
Closing was mistake.   Intended to only add comment.

**Comment by nmhamster** [comment]
Note that this error is reproducible *across* platforms, not within a single platform. Despite using a fixed random number generator which works across machines, the output is not the same when we move between different operating systems and compilers.

**Comment by nmhamster** [comment]
Moved to attic, shelved for future.
