### ISSUE TITLE
FFT3D runs with infinite time

### ISSUE THREAD

**Issue by timothychong-hpe** [sstsimulator/sst-elements#761]
New Issue for sst-elements
--------------------------

1 - Detailed description of problem or enhancement
FFT3D runs with error "Event queue empty" and simulated time > 18Ms. It works normally with an older sst-element commit: 32f2edb. (one of the releases)

2 - Describe how to reproduce
checkout sst-element commit 32f2edb. 
run FFT3D with npRow=16
--topo=torus
--numRanksPerNode=1
--shape=4x4

3 - What Operating system(s) and versions 
Ubuntu

4 - What version of external libraries (Boost, MPI)
should be irrelevant

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
Previous working version: 32f2edb
Current master: db5baf94b8a

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by mjleven** [comment]
PR 832 fixes this.
