### ISSUE TITLE
SysC component does not build

### ISSUE THREAD

**Issue by KarateSnowMachine** [sstsimulator/sst-elements#791]
It appears that there have been some changes to the `memHierarchy` element that have caused the SysC element to stop compiling. Some of the errors I can fix by inspection, but was wondering if someone with more detailed knowledge of the code could take a look at this. 

It looks like there was a major restructuring of the memHierarchy module in 1ef4f8faa4 back in May. Some of the changes that are causing breakages are: 

* updates to memHierarchy commands table
* removal of the `event.setGrantedState()` function
* attempt to access the systemc sc_simcontext `m_time_params` 
* other things I haven't found yet

**Comment by hughes-c** [comment]
Closing this as SysC was removed in SST-9.0.

http://sst-simulator.org/SSTPages/SSTmicroReleaseV9dot0dot0/
