### ISSUE TITLE
No documentation (commandline) on how to run a motif

### ISSUE THREAD

**Issue by chabbimilind** [sstsimulator/sst-elements#806]
New Issue for sst-elements
--------------------------

1 - Detailed description of problem or enhancement
I am looking to run some of the ember motifs and there exists no documentation and help on the commandline to use for running a motif. Please add the documentation on how to run a motif.

2 - Describe how to reproduce
N/A

3 - What Operating system(s) and versions 
N/A

4 - What version of external libraries (Boost, MPI)
N/A

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
N/A

6 - Fill out Labels, Milestones, and Assignee fields as best possible
N/A

**Comment by allevin** [comment]
No further response from author, closing this issue.
