### ISSUE TITLE
core/output.h needs debugPrefix

### ISSUE THREAD

**Issue by mjleven** [sstsimulator/sst-elements#937]
output.h has debug() and verbose() member functions the only difference between the two is that debug ifdefs out the the body of the function via #ifdef __SST_DEBUG_OUTPUT__. It would be handy to have debugPrefix() which supports the prefix like verbosePrefix() but ifdef's out the body of the function like debug().

**Comment by nmhamster** [comment]
@mjleven - this feature was added in SHA: 5aec9277e in SST-Core (https://github.com/sstsimulator/sst-core/pull/364). Closing, please re-open if needed or have any issues.
