### ISSUE TITLE
Boost Releases > 1.56 do not work with SST.  Need demo case.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-elements#94]
Need a test case for Boost serialization failure using version higher than 1.56 !

**Comment by nmhamster** [comment]
I think 1.57 still works right? Its working on my Mac but anything else is broken.

**Comment by jwilso** [comment]
Currently installing 1.61 Boost on all platforms.  Will send out notice once this is complete so that tests can be run against this version to confirm that this is closed.

**Comment by nmhamster** [comment]
@jwilso @jpvandy does it look like the early Boost installs are performing OK?

**Comment by jwilso** [comment]
I think there are some 1.61 test cases, but I don’t think it is being evaluated everywhere it is installed.  Nor are we evaluating intermediate revisions between 1.56 and 1.61.

J.

--
Jon Wilson
SST Software Engineering/Quality Assurance
CSRI
Sandia National Laboratories

**Comment by nmhamster** [comment]
1.56 is used for SST v6.0 release.
