### ISSUE TITLE
configure doesn't check that the compiler supports supports static template instantiation

### ISSUE THREAD

**Issue by mjleven** [sstsimulator/sst-elements#943]
The new ELI format relies on compiler support for static template instantiation. If the compiler doesn't support it  libraries that have been  ported to the new ELI format are not found even though they are present.

**Comment by jwilso** [comment]
@mjleven @mjleven Is this still an issue? The ELI has changed since this was submitted.

**Comment by allevin** [comment]
No further response from author, closing this issue.
