### ISSUE TITLE
Does SST support Ramulator?

### ISSUE THREAD

**Issue by sataei** [sstsimulator/sst-elements#966]

**Comment by gvoskuilen** [comment]
Yes, Ramulator has been integrated as a memHierarchy memory backend model. Configure sst-elements with "--with-ramulator=$RAMULATOR_DIR".

**Comment by sataei** [comment]
@allevin I am using Linux and I wasn't able to add Ramulator to SST by @gvoskuilen instructions. Would you please send me your patches?

**Comment by allevin** [comment]
@sataei  Make sure you are getting ramulator from https://github.com/CMU-SAFARI/ramulator and using the master branch.  I have included both in a zip file (GitHub won't let me attach them separately.)  

Normally ramulator does not compile using gcc 4.8, but these changes seem to fix this.  We have not yet implemented formal testing yet with SST so there might still be problems.  Let me know how this works out.

To build for OSX: use `> make libramulator.a`
To build for Linux: use `> make CXX=g++ libramulator.so`

[ramulator_sha_7d2e72_patches.zip](https://github.com/sstsimulator/sst-elements/files/1932692/ramulator_sha_7d2e72_patches.zip)

**Comment by nmhamster** [comment]
@sataei - closing the issue. Please let us know if you have any further questions.
