### ISSUE TITLE
Does SST still support Gem5 now?

### ISSUE THREAD

**Issue by lwj0012** [sstsimulator/sst-elements#970]
I am trying to build the latest SST (which is 7.2) with the Gem5 (the official version from the trunk), but when I try to compile the sst-gem5 from the gem5 root directory (which is according to the README file in the Gem5/ext/sst), there is an error, "want_info" not found.
Is this an error caused by version mismatch? Or, what version should be used to run Gem5 with SST?
Thanks.

**Comment by hughes-c** [comment]
We no longer test with gem5. Maybe @afrodri can tell you version of SST known to work.
