### ISSUE TITLE
Difficulty in accessing VaultSimC independent of the sst core.

### ISSUE THREAD

**Issue by LeulW** [sstsimulator/sst-elements#975]
Is it possible to have access to the standalone version of the sst-element VaultSimC in order to use it independently of the sst-core? 
The current implementation code of VaultSimC  contains references to the sst framework. Can it be made accessible like any other external elements such as DRAMSim2 and HMCSIM for standalone use?

**Comment by allevin** [comment]
No further response from author, closing this issue.
